import type { LoggerOptions } from "pino";

export const logRedaction: NonNullable<LoggerOptions["redact"]> = {
  paths: [
    "authorization",
    "cookie",
    "headers.authorization",
    "headers.cookie",
    "req.headers.authorization",
    "req.headers.cookie",
    "req.body",
    "res.body",
    "privateKey",
    "walletPrivateKey",
    "documentEncryptionPrivateKey",
    "privateEncryptionKey",
    "publicEncryptionKey",
    "aesKey",
    "rawKey",
    "wrappedAESKey",
    "wrappedKey",
    "wrappedKeyContents",
    "password",
    "seedPhrase",
    "file",
    "fileContents",
    "encryptedFile",
    "encryptedFileContents",
    "MONGODB_URI",
    "mongoUri",
    "mongodbUri",
    "connectionString",
    "*.authorization",
    "*.cookie",
    "*.privateKey",
    "*.walletPrivateKey",
    "*.documentEncryptionPrivateKey",
    "*.privateEncryptionKey",
    "*.publicEncryptionKey",
    "*.aesKey",
    "*.rawKey",
    "*.wrappedAESKey",
    "*.wrappedKey",
    "*.wrappedKeyContents",
    "*.password",
    "*.seedPhrase",
    "*.file",
    "*.fileContents",
    "*.encryptedFile",
    "*.encryptedFileContents",
    "*.MONGODB_URI",
    "*.mongoUri",
    "*.mongodbUri",
    "*.connectionString"
  ],
  remove: true
};
